kind: Service
apiVersion: v1
metadata:
  name: api-google-earth-historical-imagery
spec:
  selector:
    app: smart-crawler
    kind: api-google-earth-historical-imagery
  type: LoadBalancer
  ports:
    - name: api
      protocol: TCP
      port: 30099
      targetPort: 4444
      nodePort: 30099
  externalIPs:
    - 10.11.121.101
    - 10.11.121.102
    - 10.11.121.103
